apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-app
  namespace: hello-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python-container
        image: b37775b30994/hello-python-app:latest
        ports:
        - containerPort: 5000
