apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: hello-python
spec:
  type: NodePort
  selector:
    app: hello-python
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
